//
// Generated file, do not edit! Created by opp_msgtool 6.0 from apps/alert/AlertPacket.msg.
//

#ifndef __ALERTPACKET_M_H
#define __ALERTPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class AlertPacket;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>apps/alert/AlertPacket.msg:20</tt> by opp_msgtool.
 * <pre>
 * class AlertPacket extends inet::FieldsChunk
 * {
 *     unsigned int sno;
 *     simtime_t payloadTimestamp;
 * }
 * </pre>
 */
class AlertPacket : public ::inet::FieldsChunk
{
  protected:
    unsigned int sno = 0;
    omnetpp::simtime_t payloadTimestamp = SIMTIME_ZERO;

  private:
    void copy(const AlertPacket& other);

  protected:
    bool operator==(const AlertPacket&) = delete;

  public:
    AlertPacket();
    AlertPacket(const AlertPacket& other);
    virtual ~AlertPacket();
    AlertPacket& operator=(const AlertPacket& other);
    virtual AlertPacket *dup() const override {return new AlertPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getSno() const;
    virtual void setSno(unsigned int sno);

    virtual omnetpp::simtime_t getPayloadTimestamp() const;
    virtual void setPayloadTimestamp(omnetpp::simtime_t payloadTimestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AlertPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AlertPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline AlertPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<AlertPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ALERTPACKET_M_H

