//
// Generated file, do not edit! Created by opp_msgtool 6.0 from apps/burst/BurstPacket.msg.
//

#ifndef __BURSTPACKET_M_H
#define __BURSTPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class BurstPacket;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>apps/burst/BurstPacket.msg:20</tt> by opp_msgtool.
 * <pre>
 * //
 * // Packet used by the ~BurstSender and ~BurstReceiver modules.
 * //
 * class BurstPacket extends inet::FieldsChunk
 * {
 *     unsigned int msgId;
 *     simtime_t arrivalTime;
 *     simtime_t payloadTimestamp;
 *     unsigned int payloadSize;
 * }
 * </pre>
 */
class BurstPacket : public ::inet::FieldsChunk
{
  protected:
    unsigned int msgId = 0;
    omnetpp::simtime_t arrivalTime = SIMTIME_ZERO;
    omnetpp::simtime_t payloadTimestamp = SIMTIME_ZERO;
    unsigned int payloadSize = 0;

  private:
    void copy(const BurstPacket& other);

  protected:
    bool operator==(const BurstPacket&) = delete;

  public:
    BurstPacket();
    BurstPacket(const BurstPacket& other);
    virtual ~BurstPacket();
    BurstPacket& operator=(const BurstPacket& other);
    virtual BurstPacket *dup() const override {return new BurstPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getMsgId() const;
    virtual void setMsgId(unsigned int msgId);

    virtual omnetpp::simtime_t getArrivalTime() const;
    virtual void setArrivalTime(omnetpp::simtime_t arrivalTime);

    virtual omnetpp::simtime_t getPayloadTimestamp() const;
    virtual void setPayloadTimestamp(omnetpp::simtime_t payloadTimestamp);

    virtual unsigned int getPayloadSize() const;
    virtual void setPayloadSize(unsigned int payloadSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BurstPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BurstPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline BurstPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<BurstPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __BURSTPACKET_M_H

