//
// Generated file, do not edit! Created by opp_msgtool 6.0 from nodes/mec/MECPlatform/MEAppPacket.msg.
//

#ifndef __MEAPPPACKET_M_H
#define __MEAPPPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class MEAppPacket;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>nodes/mec/MECPlatform/MEAppPacket.msg:15</tt> by opp_msgtool.
 * <pre>
 * class MEAppPacket extends inet::FieldsChunk
 * {
 *     unsigned int sno;
 *     simtime_t timestamp;
 * 
 *     //type of message
 *     string type;
 * 
 *     //communication informations
 *     string sourceAddress;
 *     int sourcePort;   // added by Alessandro Noferi
 *     string destinationAddress;
 *     int destinationPort;   // added by Alessandro Noferi
 *     string destinationMecAppAddress;
 *     int destinationMecAppPort;   // added by Alessandro Noferi
 * 
 * 
 *     //instantiation informations
 *     string MEModuleType;			//path where to find the cModule of the MEApp to instantiate
 *     string MEModuleName;			//module class name of the MEApp to instantiate
 * 
 *     //identification information
 *     int ueAppID;
 * 
 *     //resources required
 *     double requiredDisk;
 *     double requiredRam;
 *     double requiredCpu;
 * 
 *     //service required
 *     string requiredService;
 * }
 * </pre>
 */
class MEAppPacket : public ::inet::FieldsChunk
{
  protected:
    unsigned int sno = 0;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    omnetpp::opp_string type;
    omnetpp::opp_string sourceAddress;
    int sourcePort = 0;
    omnetpp::opp_string destinationAddress;
    int destinationPort = 0;
    omnetpp::opp_string destinationMecAppAddress;
    int destinationMecAppPort = 0;
    omnetpp::opp_string MEModuleType;
    omnetpp::opp_string MEModuleName;
    int ueAppID = 0;
    double requiredDisk = 0;
    double requiredRam = 0;
    double requiredCpu = 0;
    omnetpp::opp_string requiredService;

  private:
    void copy(const MEAppPacket& other);

  protected:
    bool operator==(const MEAppPacket&) = delete;

  public:
    MEAppPacket();
    MEAppPacket(const MEAppPacket& other);
    virtual ~MEAppPacket();
    MEAppPacket& operator=(const MEAppPacket& other);
    virtual MEAppPacket *dup() const override {return new MEAppPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getSno() const;
    virtual void setSno(unsigned int sno);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);

    virtual const char * getType() const;
    virtual void setType(const char * type);

    virtual const char * getSourceAddress() const;
    virtual void setSourceAddress(const char * sourceAddress);

    virtual int getSourcePort() const;
    virtual void setSourcePort(int sourcePort);

    virtual const char * getDestinationAddress() const;
    virtual void setDestinationAddress(const char * destinationAddress);

    virtual int getDestinationPort() const;
    virtual void setDestinationPort(int destinationPort);

    virtual const char * getDestinationMecAppAddress() const;
    virtual void setDestinationMecAppAddress(const char * destinationMecAppAddress);

    virtual int getDestinationMecAppPort() const;
    virtual void setDestinationMecAppPort(int destinationMecAppPort);

    virtual const char * getMEModuleType() const;
    virtual void setMEModuleType(const char * MEModuleType);

    virtual const char * getMEModuleName() const;
    virtual void setMEModuleName(const char * MEModuleName);

    virtual int getUeAppID() const;
    virtual void setUeAppID(int ueAppID);

    virtual double getRequiredDisk() const;
    virtual void setRequiredDisk(double requiredDisk);

    virtual double getRequiredRam() const;
    virtual void setRequiredRam(double requiredRam);

    virtual double getRequiredCpu() const;
    virtual void setRequiredCpu(double requiredCpu);

    virtual const char * getRequiredService() const;
    virtual void setRequiredService(const char * requiredService);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MEAppPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MEAppPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline MEAppPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<MEAppPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MEAPPPACKET_M_H

