#! /bin/sh

case "$-" in
*i*) ;;
*)  if [ "$1" != "-f" ]; then # allow use from scripts, as ". setenv -f"
        echo "Error: not a login shell -- run this script as 'source setenv' or '. setenv'"
        exit 1
    fi
esac

if [ ! -f bin/tsn5g ]; then
    echo "Error: current working directory does not look like a tsnfivegcomm root directory"
    # no exit -- it would close the shell
else
    export TSN5G_ROOT=`pwd`
    echo "$TSN5G_ROOT added to PATH"
    export PATH=$TSN5G_ROOT/bin:$PATH
fi

