//
// Generated file, do not edit! Created by opp_msgtool 6.0 from common/timer/TMultiTimerMsg.msg.
//

#ifndef __TMULTITIMERMSG_M_H
#define __TMULTITIMERMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TMultiTimerMsg;
#include "common/timer/TTimerMsg_m.h" // import common.timer.TTimerMsg

/**
 * Class generated from <tt>common/timer/TMultiTimerMsg.msg:15</tt> by opp_msgtool.
 * <pre>
 * packet TMultiTimerMsg extends TTimerMsg
 * {
 *     unsigned int event;
 * }
 * </pre>
 */
class TMultiTimerMsg : public ::TTimerMsg
{
  protected:
    unsigned int event = 0;

  private:
    void copy(const TMultiTimerMsg& other);

  protected:
    bool operator==(const TMultiTimerMsg&) = delete;

  public:
    TMultiTimerMsg(const char *name=nullptr, short kind=0);
    TMultiTimerMsg(const TMultiTimerMsg& other);
    virtual ~TMultiTimerMsg();
    TMultiTimerMsg& operator=(const TMultiTimerMsg& other);
    virtual TMultiTimerMsg *dup() const override {return new TMultiTimerMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getEvent() const;
    virtual void setEvent(unsigned int event);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TMultiTimerMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TMultiTimerMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TMultiTimerMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<TMultiTimerMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TMULTITIMERMSG_M_H

