//
// Generated file, do not edit! Created by opp_msgtool 6.0 from apps/d2dMultihop/TrickleTimerMsg.msg.
//

#ifndef __TRICKLETIMERMSG_M_H
#define __TRICKLETIMERMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TrickleTimerMsg;
/**
 * Class generated from <tt>apps/d2dMultihop/TrickleTimerMsg.msg:13</tt> by opp_msgtool.
 * <pre>
 * message TrickleTimerMsg
 * {
 *     uint32_t msgid;          // unique id of the message  < sender id  | local msg id >
 * }
 * </pre>
 */
class TrickleTimerMsg : public ::omnetpp::cMessage
{
  protected:
    uint32_t msgid = 0;

  private:
    void copy(const TrickleTimerMsg& other);

  protected:
    bool operator==(const TrickleTimerMsg&) = delete;

  public:
    TrickleTimerMsg(const char *name=nullptr, short kind=0);
    TrickleTimerMsg(const TrickleTimerMsg& other);
    virtual ~TrickleTimerMsg();
    TrickleTimerMsg& operator=(const TrickleTimerMsg& other);
    virtual TrickleTimerMsg *dup() const override {return new TrickleTimerMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint32_t getMsgid() const;
    virtual void setMsgid(uint32_t msgid);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TrickleTimerMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TrickleTimerMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TrickleTimerMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<TrickleTimerMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TRICKLETIMERMSG_M_H

