//
// Generated file, do not edit! Created by opp_msgtool 6.0 from stack/sdap/packet/SdapPdu.msg.
//

#ifndef __SDAPPDU_M_H
#define __SDAPPDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SdapPdu;
/**
 * Class generated from <tt>stack/sdap/packet/SdapPdu.msg:20</tt> by opp_msgtool.
 * <pre>
 * packet SdapPdu
 * {
 * }
 * </pre>
 */
class SdapPdu : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const SdapPdu& other);

  protected:
    bool operator==(const SdapPdu&) = delete;

  public:
    SdapPdu(const char *name=nullptr, short kind=0);
    SdapPdu(const SdapPdu& other);
    virtual ~SdapPdu();
    SdapPdu& operator=(const SdapPdu& other);
    virtual SdapPdu *dup() const override {return new SdapPdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SdapPdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SdapPdu& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SdapPdu *fromAnyPtr(any_ptr ptr) { return check_and_cast<SdapPdu*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SDAPPDU_M_H

